title: "Will Russell"
email: fellowship@mlh.io
role: "Software Developer"
employer: "Cool Company"
bio_text: "This is an example of some bio text that may be placed below the job title"
description: >- # this means to ignore newlines until "baseurl:"
  This is my portfolio website!
baseurl: "pod-3.1.1-portfolio"
url: "/"
twitter_username: mlhacks
github_username: mlh-fellowship

sass:
  sass_dir: _sass

icon: /assets/img/icon.jpg
